name: CI-CD-Self-Reward-API

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install fastapi uvicorn httpx pytest bandit

      - name: Run Unit Test (CI)
        run: |
          pytest

      - name: Security Scan (CS)
        run: |
          bandit -r app/